version: '3.9'
services:
  web:
    build: .
    command: daphne -b 0.0.0.0 -p 8000 speedproj.asgi:application
    ports:
      - "8000:8000"
    environment:
      - REDIS_URL=redis://redis:6379/0
      - DEBUG=False
      - ALLOWED_HOSTS=localhost,127.0.0.1
    depends_on:
      - redis
  redis:
    image: redis:7
    restart: unless-stopped
    ports:
      - "6379:6379"
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./deployment/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - web
